/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import civitas.Casilla;
import civitas.CasillaCalle;
import civitas.CasillaImpuesto;
import civitas.CasillaJuez;
import civitas.CasillaSorpresa;
/**
 *
 * @author sergio
 */
public class CasillaPanel extends javax.swing.JPanel {

    private Casilla casilla;
    /**
     * Creates new form CasillaPanel
     */
    public CasillaPanel() {
        initComponents();
        visibilidad(false);
    }
    
    public void setCasilla(Casilla casilla){
        this.casilla = casilla;
        nombreCasilla.setText(this.casilla.getNombre());
        String s = new String();
        visibilidad(false);
        
        if(casilla.getClass() == CasillaCalle.class){
            s = "Calle";

            importepropi.setText("Propietario: ");
            
            casasCasilla.setText(Integer.toString(((CasillaCalle)this.casilla).getTituloPropiedad().getNumCasas()));
            hotelesCasilla.setText(Integer.toString(((CasillaCalle)this.casilla).getTituloPropiedad().getNumHoteles()));
            compraCasilla.setText(Float.toString(((CasillaCalle)this.casilla).getTituloPropiedad().getPrecioCompra()));
            if(((CasillaCalle)this.casilla).getTituloPropiedad().getPropietario() != null){
                casas.setVisible(true);
                hoteles.setVisible(true);
                casasCasilla.setVisible(true);
                hotelesCasilla.setVisible(true);
                importepropi.setVisible(true);
                alquiler.setVisible(true);
                alquilerCasilla.setVisible(true);
                alquilerCasilla.setText(Float.toString(((CasillaCalle)this.casilla).getTituloPropiedad().getPrecioAlquiler()));
                importepropiCasilla.setText(((CasillaCalle)this.casilla).getTituloPropiedad().getPropietario().getNombre());
                importepropiCasilla.setVisible(true);
            }
            else{
                compra.setVisible(true);
                compraCasilla.setVisible(true);
            }
            
            
        }
        else if(this.casilla.getClass() == CasillaImpuesto.class){
            s = "Impuesto";
            importepropi.setVisible(true);          
            importepropi.setVisible(true);
            importepropi.setText("Impuesto: ");
            importepropiCasilla.setText(Float.toString(((CasillaImpuesto)this.casilla).getImporte()));
        }
        else if(this.casilla.getClass() == CasillaJuez.class){
            s = "Juez";
        }
        else if(this.casilla.getClass() == CasillaSorpresa.class){
            s = "Sorpresa";
        }
        else if(this.casilla.getClass() == Casilla.class){
            s = "Descanso";
        }

        tipoCasilla.setText(s);
        setVisible(true);
        repaint();
        revalidate();
    }

    private void visibilidad(boolean v){
        compraCasilla.setVisible(v);
        casasCasilla.setVisible(v);
        hotelesCasilla.setVisible(v);
        importepropiCasilla.setVisible(v);
        alquilerCasilla.setVisible(v);
        compra.setVisible(v);
        casas.setVisible(v);
        hoteles.setVisible(v);
        importepropi.setVisible(v);
        alquiler.setVisible(v);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        importepropi = new javax.swing.JLabel();
        alquiler = new javax.swing.JLabel();
        casas = new javax.swing.JLabel();
        hoteles = new javax.swing.JLabel();
        nombreCasilla = new javax.swing.JTextField();
        tipoCasilla = new javax.swing.JTextField();
        importepropiCasilla = new javax.swing.JTextField();
        alquilerCasilla = new javax.swing.JTextField();
        casasCasilla = new javax.swing.JTextField();
        hotelesCasilla = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        compra = new javax.swing.JLabel();
        compraCasilla = new javax.swing.JTextField();

        nombre.setText("Nombre: ");
        nombre.setEnabled(false);

        tipo.setText("Tipo:");
        tipo.setEnabled(false);

        importepropi.setText("Importe:");
        importepropi.setEnabled(false);

        alquiler.setText("Alquiler:");
        alquiler.setEnabled(false);

        casas.setText("Casas:");
        casas.setEnabled(false);

        hoteles.setText("Hoteles:");
        hoteles.setEnabled(false);

        nombreCasilla.setText("nombreCasilla");
        nombreCasilla.setEnabled(false);

        tipoCasilla.setText("tipoCasilla");
        tipoCasilla.setEnabled(false);

        importepropiCasilla.setText("imppropiCasilla");
        importepropiCasilla.setEnabled(false);
        importepropiCasilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importepropiCasillaActionPerformed(evt);
            }
        });

        alquilerCasilla.setText("alquilerCasilla");
        alquilerCasilla.setEnabled(false);

        casasCasilla.setText("casasCasilla");
        casasCasilla.setEnabled(false);

        hotelesCasilla.setText("hotelesCasilla");
        hotelesCasilla.setEnabled(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CASILLA");
        jLabel1.setEnabled(false);

        compra.setText("Compra:");
        compra.setEnabled(false);

        compraCasilla.setText("compraCasilla");
        compraCasilla.setEnabled(false);
        compraCasilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraCasillaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(compra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compraCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alquiler)
                            .addComponent(importepropi)
                            .addComponent(nombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombreCasilla)
                            .addComponent(importepropiCasilla, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alquilerCasilla)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hoteles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hotelesCasilla))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipoCasilla))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(casas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casasCasilla)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(nombreCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo)
                    .addComponent(tipoCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(importepropi)
                    .addComponent(importepropiCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alquiler)
                    .addComponent(alquilerCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casas)
                    .addComponent(casasCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoteles)
                    .addComponent(hotelesCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compra)
                    .addComponent(compraCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void compraCasillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compraCasillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compraCasillaActionPerformed

    private void importepropiCasillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importepropiCasillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_importepropiCasillaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alquiler;
    private javax.swing.JTextField alquilerCasilla;
    private javax.swing.JLabel casas;
    private javax.swing.JTextField casasCasilla;
    private javax.swing.JLabel compra;
    private javax.swing.JTextField compraCasilla;
    private javax.swing.JLabel hoteles;
    private javax.swing.JTextField hotelesCasilla;
    private javax.swing.JLabel importepropi;
    private javax.swing.JTextField importepropiCasilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombreCasilla;
    private javax.swing.JLabel tipo;
    private javax.swing.JTextField tipoCasilla;
    // End of variables declaration//GEN-END:variables
}
