/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import civitas.TituloPropiedad;
/**
 *
 * @author sergio
 */
public class PropiedadPanel extends javax.swing.JPanel {

    private TituloPropiedad tituloPropiedad;
    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }

    void setPropiedad(TituloPropiedad titulo){
        tituloPropiedad = titulo;
        tituloPropi.setText(tituloPropiedad.getNombre());
        casasPropi.setText(Integer.toString(tituloPropiedad.getNumCasas()));
        hotelesPropi.setText(Integer.toString(tituloPropiedad.getNumHoteles()));
        hipotecadaPropi.setText(Boolean.toString(tituloPropiedad.getHipotecado()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        casas = new javax.swing.JLabel();
        hoteles = new javax.swing.JLabel();
        hipotecada = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        tituloPropi = new javax.swing.JTextField();
        casasPropi = new javax.swing.JTextField();
        hotelesPropi = new javax.swing.JTextField();
        hipotecadaPropi = new javax.swing.JTextField();
        propiedad = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(212, 159));

        casas.setText("Numero de casas:");
        casas.setEnabled(false);

        hoteles.setText("Numero de hoteles:");
        hoteles.setEnabled(false);

        hipotecada.setText("Hipotecada:");
        hipotecada.setEnabled(false);

        titulo.setText("Titulo:");
        titulo.setEnabled(false);

        tituloPropi.setText("tituloPropiedad");
        tituloPropi.setEnabled(false);
        tituloPropi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloPropiActionPerformed(evt);
            }
        });

        casasPropi.setText("casasPropiedad");
        casasPropi.setEnabled(false);

        hotelesPropi.setText("hotelesPropiedad");
        hotelesPropi.setEnabled(false);

        hipotecadaPropi.setText("hipotecadaPropiedad");
        hipotecadaPropi.setEnabled(false);

        propiedad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        propiedad.setText("PROPIEDAD");
        propiedad.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propiedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hipotecada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hipotecadaPropi, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tituloPropi, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casas)
                            .addComponent(hoteles))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casasPropi, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(hotelesPropi, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(propiedad)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo)
                    .addComponent(tituloPropi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casas)
                    .addComponent(casasPropi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoteles)
                    .addComponent(hotelesPropi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hipotecada)
                    .addComponent(hipotecadaPropi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tituloPropiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloPropiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloPropiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel casas;
    private javax.swing.JTextField casasPropi;
    private javax.swing.JLabel hipotecada;
    private javax.swing.JTextField hipotecadaPropi;
    private javax.swing.JLabel hoteles;
    private javax.swing.JTextField hotelesPropi;
    private javax.swing.JLabel propiedad;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField tituloPropi;
    // End of variables declaration//GEN-END:variables
}
